<?xml version="1.0" encoding="utf-8"?><Database Name="NET_OCA" Class="BancoDadosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=mg0000dv0001\mssql2008;Initial Catalog=NET_OCA;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="NET_OCAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbCliente" Member="tbClientes">
    <Type Name="tbCliente">
      <Column Name="cpf" Type="System.String" DbType="Char(11) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nome" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefoneresidencial" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="endereco" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="datanascimento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="numerocelular" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>