#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NET_OCA")]
	public partial class BancoDadosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbCliente(tbCliente instance);
    partial void UpdatetbCliente(tbCliente instance);
    partial void DeletetbCliente(tbCliente instance);
    #endregion
		
		public BancoDadosDataContext() : 
				base(global::DAL.Properties.Settings.Default.NET_OCAConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDadosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDadosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDadosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BancoDadosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbCliente> tbClientes
		{
			get
			{
				return this.GetTable<tbCliente>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbCliente")]
	public partial class tbCliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cpf;
		
		private string _nome;
		
		private string _telefoneresidencial;
		
		private string _endereco;
		
		private System.Nullable<System.DateTime> _datanascimento;
		
		private string _numerocelular;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncpfChanging(string value);
    partial void OncpfChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OntelefoneresidencialChanging(string value);
    partial void OntelefoneresidencialChanged();
    partial void OnenderecoChanging(string value);
    partial void OnenderecoChanged();
    partial void OndatanascimentoChanging(System.Nullable<System.DateTime> value);
    partial void OndatanascimentoChanged();
    partial void OnnumerocelularChanging(string value);
    partial void OnnumerocelularChanged();
    #endregion
		
		public tbCliente()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf", DbType="Char(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cpf
		{
			get
			{
				return this._cpf;
			}
			set
			{
				if ((this._cpf != value))
				{
					this.OncpfChanging(value);
					this.SendPropertyChanging();
					this._cpf = value;
					this.SendPropertyChanged("cpf");
					this.OncpfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nome
		{
			get
			{
				return this._nome;
			}
			set
			{
				if ((this._nome != value))
				{
					this.OnnomeChanging(value);
					this.SendPropertyChanging();
					this._nome = value;
					this.SendPropertyChanged("nome");
					this.OnnomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefoneresidencial", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string telefoneresidencial
		{
			get
			{
				return this._telefoneresidencial;
			}
			set
			{
				if ((this._telefoneresidencial != value))
				{
					this.OntelefoneresidencialChanging(value);
					this.SendPropertyChanging();
					this._telefoneresidencial = value;
					this.SendPropertyChanged("telefoneresidencial");
					this.OntelefoneresidencialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endereco", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string endereco
		{
			get
			{
				return this._endereco;
			}
			set
			{
				if ((this._endereco != value))
				{
					this.OnenderecoChanging(value);
					this.SendPropertyChanging();
					this._endereco = value;
					this.SendPropertyChanged("endereco");
					this.OnenderecoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_datanascimento", DbType="DateTime")]
		public System.Nullable<System.DateTime> datanascimento
		{
			get
			{
				return this._datanascimento;
			}
			set
			{
				if ((this._datanascimento != value))
				{
					this.OndatanascimentoChanging(value);
					this.SendPropertyChanging();
					this._datanascimento = value;
					this.SendPropertyChanged("datanascimento");
					this.OndatanascimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numerocelular", DbType="VarChar(10)")]
		public string numerocelular
		{
			get
			{
				return this._numerocelular;
			}
			set
			{
				if ((this._numerocelular != value))
				{
					this.OnnumerocelularChanging(value);
					this.SendPropertyChanging();
					this._numerocelular = value;
					this.SendPropertyChanged("numerocelular");
					this.OnnumerocelularChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
