//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCliente.ServicoIntegracao {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbCliente", Namespace="http://schemas.datacontract.org/2004/07/DAL")]
    [System.SerializableAttribute()]
    public partial class tbCliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> datanascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string enderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numerocelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefoneresidencialField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                if ((object.ReferenceEquals(this.cpfField, value) != true)) {
                    this.cpfField = value;
                    this.RaisePropertyChanged("cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> datanascimento {
            get {
                return this.datanascimentoField;
            }
            set {
                if ((this.datanascimentoField.Equals(value) != true)) {
                    this.datanascimentoField = value;
                    this.RaisePropertyChanged("datanascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string endereco {
            get {
                return this.enderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.enderecoField, value) != true)) {
                    this.enderecoField = value;
                    this.RaisePropertyChanged("endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                if ((object.ReferenceEquals(this.nomeField, value) != true)) {
                    this.nomeField = value;
                    this.RaisePropertyChanged("nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numerocelular {
            get {
                return this.numerocelularField;
            }
            set {
                if ((object.ReferenceEquals(this.numerocelularField, value) != true)) {
                    this.numerocelularField = value;
                    this.RaisePropertyChanged("numerocelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefoneresidencial {
            get {
                return this.telefoneresidencialField;
            }
            set {
                if ((object.ReferenceEquals(this.telefoneresidencialField, value) != true)) {
                    this.telefoneresidencialField = value;
                    this.RaisePropertyChanged("telefoneresidencial");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoIntegracao.IServicoIntegracao")]
    public interface IServicoIntegracao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoIntegracao/Pesquisar", ReplyAction="http://tempuri.org/IServicoIntegracao/PesquisarResponse")]
        WebCliente.ServicoIntegracao.tbCliente Pesquisar(string cpf);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicoIntegracao/Atualizar", ReplyAction="http://tempuri.org/IServicoIntegracao/AtualizarResponse")]
        void Atualizar(WebCliente.ServicoIntegracao.tbCliente cliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicoIntegracaoChannel : WebCliente.ServicoIntegracao.IServicoIntegracao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoIntegracaoClient : System.ServiceModel.ClientBase<WebCliente.ServicoIntegracao.IServicoIntegracao>, WebCliente.ServicoIntegracao.IServicoIntegracao {
        
        public ServicoIntegracaoClient() {
        }
        
        public ServicoIntegracaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoIntegracaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoIntegracaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoIntegracaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebCliente.ServicoIntegracao.tbCliente Pesquisar(string cpf) {
            return base.Channel.Pesquisar(cpf);
        }
        
        public void Atualizar(WebCliente.ServicoIntegracao.tbCliente cliente) {
            base.Channel.Atualizar(cliente);
        }
    }
}
